services:
  ito-grpc-server:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - path: ./.env
        required: false
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run start
    container_name: ito-server
    restart: always
    depends_on:
      - whisper
    environment:
      NODE_ENV: development
      LOCAL_WHISPER_BASE_URL: http://whisper:8000

  whisper:
    image: ghcr.io/speaches-ai/speaches:latest-cpu
    container_name: ito-whisper
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - whisper_models:/home/ubuntu/.cache/huggingface/hub

volumes:
  whisper_models:
